version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - beeshop-network
    restart: unless-stopped

networks:
  beeshop-network:
    external: true
